name: Setup RClone
description: "Load protected env JSON, fetch/install rclone config, then POST the on-disk rclone.conf"
inputs:
  env_url:
    description: "Protected JSON URL"
    required: true
  env_token:
    description: "Bearer or token for the protected JSON"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Load Remote ENV from Protected JSON
      uses: subekti404dev/gha-json-env@v1
      with:
        url: ${{ inputs.env_url }}
        token: ${{ inputs.env_token }}

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    # GETTER (fills B64_RCLONE into $GITHUB_ENV)
    - name: Fetch rclone config (base64) via JS
      shell: bash
      env:
        RCLONE_GETTER_URL: ${{ env.rclone_getter_url }}
      run: node scripts/rclone-getter.js

    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: ${{ env.B64_RCLONE }}

    # SETTER (reads ~/.config/rclone/rclone.conf and POSTs it)
    - name: Send rclone.conf via JS (POST, masked)
      shell: bash
      env:
        RCLONE_SETTER_URL: ${{ env.rclone_setter_url }}
      run: node scripts/rclone-setter.js
