name: Build AAB Durioo Fire TV
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to clone'
        required: false
        default: 'chore/fire-tv-2'

jobs:
  build_aab:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clone Repo
        run: git clone -b ${{ github.event.inputs.branch }} ${{ secrets.DURIOO_REPO }}

      - name: Install Utilities
        run: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo bash - 
          sudo apt-get install -y nodejs
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install Deps
        run: cd duriooplus-mobile-v2/ && yarn

      - name: Install Java 17
        uses: actions/setup-java@v1
        with:
          java-version: '17.x'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build aab
        run: cd duriooplus-mobile-v2/ && yarn build-prod-tv --local --output durioo.aab

      - name: Check Dir
        run: ls -lah

      # - name: Upload AAB
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: durioo-aab
      #     path: 'duriooplus-mobile-v2/durioo.aab'
