name: "Build iOS app"
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to clone"
        required: false
        default: "main"

jobs:
  build_with_signing:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version
      
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods -v 1.15.2

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.SNAPMEAL_BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.SNAPMEAL_P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.SNAPMEAL_BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.SNAPMEAL_KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clone Repo
        run: git clone -b ${{ github.event.inputs.branch }} ${{ secrets.SNAPMEAL_REPO }}

      - name: Install nvm and Node.js 18
        run: |
          # Install nvm
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

          # Install Node.js 18
          nvm install 18
          nvm use 18
          nvm alias default 18

      - name: Update all CURRENT_PROJECT_VERSION instances
        run: |
          # Get the version from a variable (can also come from secrets or environment)
          PROJECT_VERSION=${{ vars.SNAPMEAL_CURRENT_PROJECT_VERSION }}
          MARKETING_VERSION=${{ vars.SNAPMEAL_MARKETING_VERSION }}

          # Path to the project file
          PBXPROJ_PATH="snapmeal-mobile/ios/snapmeal.xcodeproj/project.pbxproj"

          # Use sed to replace all occurrences of CURRENT_PROJECT_VERSION
          sed -i '' "s/CURRENT_PROJECT_VERSION = [0-9]*;/CURRENT_PROJECT_VERSION = $PROJECT_VERSION;/g" $PBXPROJ_PATH
          sed -i '' "s/MARKETING_VERSION = [0-9]*;/MARKETING_VERSION = $MARKETING_VERSION;/g" $PBXPROJ_PATH
       

      - name: Install Deps
        run: |
          cd snapmeal-mobile/
          yarn
          cd ios/
          rm -rf Pods
          rm Podfile.lock
          pod cache clean --all
          RCT_NEW_ARCH_ENABLED=1 pod install --repo-update

      # - name: update min ios target
      #   run: |
      #     paths=$(find . \( -name "project.pbxproj" -o -name "Pods.xcodeproj" \))
      #     # echo "Apply patch to: $paths"
      #     for file_path in $paths; do
      #       sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9]*;/IPHONEOS_DEPLOYMENT_TARGET = 13.6;/g' "$file_path"
      #     done
      #     echo "Done setting IPHONEOS_DEPLOYMENT_TARGET"

      # - name: Update all IPHONEOS_DEPLOYMENT_TARGET instances
      #   run: |
      #     IPHONEOS_DEPLOYMENT_TARGET=${{ vars.SNAPMEAL_IPHONEOS_DEPLOYMENT_TARGET }}

      #     # Path to the project file
      #     PBXPROJ_PATH="snapmeal-mobile/ios/snapmeal.xcodeproj/project.pbxproj"

      #     # Use sed to replace all occurrences of CURRENT_PROJECT_VERSION
      #     sed -i '' "s/IPHONEOS_DEPLOYMENT_TARGET = [0-9]*;/IPHONEOS_DEPLOYMENT_TARGET = $IPHONEOS_DEPLOYMENT_TARGET;/g" $PBXPROJ_PATH

      #     # Verify if all versions are updated
      #     grep "IPHONEOS_DEPLOYMENT_TARGET" $PBXPROJ_PATH
      #     grep "CURRENT_PROJECT_VERSION" $PBXPROJ_PATH
      #     grep "MARKETING_VERSION" $PBXPROJ_PATH


      - name: build archive
        run: |
          cd snapmeal-mobile/ios
          mkdir out
          xcodebuild -scheme "snapmeal" \
          -workspace snapmeal.xcworkspace \
          -archivePath out/snapmeal.xcarchive \
          -sdk iphoneos \
          -configuration Release \
          -destination generic/platform=iOS \
          -allowProvisioningUpdates \
          -verbose \
          archive
    
      - name: list
        run: ls -lah snapmeal-mobile/ios/out

      # - name: export ipa
      #   env:
      #     EXPORT_OPTIONS_PLIST: ${{ secrets.SNAPMEAL_EXPORT_OPTIONS_PLIST }}
      #   run: |
      #     EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist
      #     echo -n "$EXPORT_OPTIONS_PLIST" | base64 --decode -o $EXPORT_OPTS_PATH
      #     xcodebuild -exportArchive -archivePath $RUNNER_TEMP/snapmeal.xcarchive -exportOptionsPlist $EXPORT_OPTS_PATH -exportPath $RUNNER_TEMP/build

      - name: Upload application
        uses: actions/upload-artifact@v3
        with:
          name: snapmeal.xcarchive
          path: snapmeal-mobile/ios/out/snapmeal.xcarchive
          # you can also archive the entire directory
          # path: ${{ runner.temp }}/build
          # retention-days: 3
