name: Build APK Snapmeal
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to clone'
        required: false
        default: 'main'

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clone Repo
        run: git clone -b ${{ github.event.inputs.branch }} ${{ secrets.SNAPMEAL_REPO }}

      - name: Install Utilities
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo bash - 
          sudo apt-get install -y nodejs

      - name: Install Deps
        run: cd snapmeal-mobile/ && yarn

      - name: Install Java 17
        uses: actions/setup-java@v1
        with:
          java-version: '17.x'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Env 
        run: echo "${{ secrets.SNAPMEAL_ENV }}" >> snapmeal-mobile/.env

      - name: Build apk
        run: cd snapmeal-mobile/android/ && ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: snapmeal-apk
          path: 'snapmeal-mobile/android/app/build/outputs/apk/release/app-release.apk'