name: Fetch ENV Example

on:
  workflow_dispatch:

jobs:
  fetch-env-demo:
    runs-on: ubuntu-latest

    steps:
      # 🧪 Step 1: Call your custom Action to fetch & set env vars
      - name: Load Remote ENV from Protected JSON
        uses: subekti404dev/gha-json-env@v1
        with:
          url: ${{ secrets.ENV_URL }}
          token: ${{ secrets.ENV_TOKEN }}

      - run: |
          echo "$database_host"
      
