name: Test Upload GDrive
on:
  workflow_dispatch:
   

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Load Remote ENV from Protected JSON
        uses: subekti404dev/gha-json-env@v1
        with:
          url: ${{ secrets.ENV_URL }}
          token: ${{ secrets.ENV_TOKEN }}

      - run: ls -lah

      
      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ env.gdrive_gha_key_b64 }}
          folderId: ${{ env.gdrive_parent_dir_id }}
          filename: "README.md"
          # name: "documentation.zip" # optional string
          overwrite: "true" # optional boolean

    
