name: Test Upload GDrive
on:
  workflow_dispatch:
   

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Load Remote ENV from Protected JSON
        uses: subekti404dev/gha-json-env@v1
        with:
          url: ${{ secrets.ENV_URL }}
          token: ${{ secrets.ENV_TOKEN }}

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ env.rclone_config_b64 }}
      
      - run: |
          sudo mkdir -p /tmp/data
          sudo touch /tmp/data/123.txt
          rclone copy /tmp/data/123.txt gdrive1:/

       # ----- Upload (mirror local -> remote) -----
      - name: Upload via FTP (recursive, passive)
        run: |
          lftp -u "${{ env.server1_ftp_user }}","${{ env.server1_ftp_pass }}" "${{ env.server1_ftp_host }}" <<'EOL'
          set ftp:passive-mode on
          set xfer:log false
          set net:max-retries 3
          set net:timeout 30
          # For FTPS (explicit TLS), uncomment:
          # set ftp:ssl-force true
          # set ftp:ssl-protect-data true
          # set ssl:verify-certificate no   # only if your cert is self-signed
          mirror -R --parallel=3 --verbose --exclude-glob .git/ ./tmp/data ./
          bye
          EOL    