name: Test Upload GDrive
on:
  workflow_dispatch:
   

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
   

      - name: Load Remote ENV from Protected JSON
        uses: subekti404dev/gha-json-env@v1
        with:
          url: ${{ secrets.ENV_URL }}
          token: ${{ secrets.ENV_TOKEN }}

      - name: Get rclone config from webhook
        id: get_rclone
        run: |
          # Fetch body text
          B64_RCLONE=$(curl -sS "${{ env.rclone_getter_url }}")
          # Store in GITHUB_ENV (makes it available to later steps)
          echo "B64_RCLONE<<EOF" >> $GITHUB_ENV
          echo "$B64_RCLONE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ env.B64_RCLONE }}
      
      - run: |
          sudo mkdir -p "$GITHUB_WORKSPACE/tmp/data"
          sudo touch "$GITHUB_WORKSPACE/tmp/data/123.txt"
          rclone copy "$GITHUB_WORKSPACE/tmp/data/123.txt" gdrive1:/


      - name: Send rclone.conf via POST (safer for large data)
        env:
          N8N_URL: ${{ env.rclone_getter_url }}
          RCLONE_CONF_PATH: ~/.config/rclone/rclone.conf
        run: |
          set -euo pipefail
          B64_CONTENT="$(base64 -w0 "$RCLONE_CONF_PATH")"
          echo "::add-mask::$B64_CONTENT"
          curl -sS \
            -H "Content-Type: application/x-www-form-urlencoded" \
            --data-urlencode "data=$B64_CONTENT" \
            "$N8N_URL"
