name: Test Upload GDrive
on:
  workflow_dispatch:
   

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load Remote ENV from Protected JSON
        uses: subekti404dev/gha-json-env@v1
        with:
          url: ${{ secrets.ENV_URL }}
          token: ${{ secrets.ENV_TOKEN }}

      - name: Decode SSH key
        id: decode_key
        run: |
          echo "key<<EOF" >> $GITHUB_OUTPUT
          echo "${{ env.pc_linux_private_ssh_b64 }}" | base64 -d >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ steps.decode_key.outputs.key }}

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ env.rclone_config_b64 }}
      
      - run: |
          touch 123.txt
          rclone copy 123.txt gdrive1:/

      - run: | 
          scp 123.txt "root@${{ env.server1_host }}:/root/"
          ls -lah

      