name: Test Upload GDrive
on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Setup RClone (composite)
        uses: subekti404dev/test-actions/.github/actions/setup-rclone@main
        with:
          env_url: ${{ secrets.ENV_URL }}
          env_token: ${{ secrets.ENV_TOKEN }}
          
      - name: Create sample file and upload
        run: |
          mkdir -p "$GITHUB_WORKSPACE/tmp/data"
          echo "hello $(date -u +%FT%TZ)" > "$GITHUB_WORKSPACE/tmp/data/123.txt"
          rclone -vv copy "$GITHUB_WORKSPACE/tmp/data/123.txt" gdrive1:/   # adjust remote/path


